{{- if .Values.EntityManager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.EntityManager.name }}
  name: {{ .Values.EntityManager.name }}
  # namespace: {{.Values.namespace}}
spec:
  replicas: {{ .Values.EntityManager.replicas }}
  selector:
    matchLabels:
      service: {{ .Values.EntityManager.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: {{ .Values.EntityManager.name }}
    spec:
      containers:
      - image: {{ .Values.EntityManager.image.repository }}:{{ .Values.EntityManager.image.tag }}
        env:
          - name: CLIENT_ID
            value: {{ .Values.EntityManager.name }}
          - name: CLIENT_SECRET
            # value: 9d93ef35-725a-4452-9c2e-cb280abe7fd1
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: entityManagerSecret
        {{- range $key, $val := .Values.postgres_vars}}
          - name: {{ $key }}
            value: {{ $val | quote }}
        {{- end }}
        {{- range $key, $val := .Values.keycloak_vars}}
          - name: {{ $key }}
            value: {{ $val | quote }}
        {{- end }}
        {{- if .Values.EntityManager.kafka_vars }}          
        {{- range $key, $val := .Values.kafka_vars }}
          - name: {{ $key }}
            value: {{ $val | quote }}
        {{- end }}
        {{- end}}
        {{- if .Values.springArgs.overrideSpringArgs }}
        env:
          - name: spring_args
            value: {{ .Values.springArgs.value }}
        {{- end}}
        imagePullPolicy: {{ .Values.EntityManager.image.pullPolicy }}
        name: {{ .Values.EntityManager.name }}
        ports:
        - containerPort: 1025
          protocol: TCP
        lifecycle:
           preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X PUT "http://eureka:8761/eureka/apps/ENTITY-MANAGER/$HOSTNAME:entity-manager:1025/status?value=OUT_OF_SERVICE"
        {{- if .Values.EntityManager.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:1025/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: {{ .Values.EntityManager.readinessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.EntityManager.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.EntityManager.readinessProbe.periodSeconds }}
          {{- end}}
        resources:
{{ toYaml .Values.EntityManager.resources | indent 10 }}
      restartPolicy: {{ .Values.EntityManager.restartPolicy }}
      {{- if .Values.EntityManager.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.EntityManager.serviceAccount.name }}
      {{- end}}
      securityContext: {{ .Values.EntityManager.securityContext | toYaml }}
      terminationGracePeriodSeconds: {{ .Values.EntityManager.terminationGracePeriodSeconds }}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.name }}
status: {}
{{- end }}