{{- if .Values.RegistryManager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.RegistryManager.name }}
  name: {{ .Values.RegistryManager.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.RegistryManager.replicas }}
  selector:
    matchLabels:
      service: {{ .Values.RegistryManager.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: {{ .Values.RegistryManager.name }}
    spec:
      containers:
      - image: {{ .Values.RegistryManager.image.repository }}:{{ .Values.RegistryManager.image.tag }}
        env:
          - name: CLIENT_ID
            value: {{ .Values.RegistryManager.name }}
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: registryManagerSecret
        {{- range $key, $val := .Values.postgres_vars}}
          - name: {{ $key }}
            value: {{ $val | quote }}
        {{- end }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ngb.{{ .Values.postgres_vars.POSTGRES_SERVICE }}.credentials.postgresql.acid.zalan.do
                key: password
        {{- range $key, $val := .Values.keycloak_vars}}
          - name: {{ $key }}
            value: {{ $val | quote }}
        {{- end }}
        {{- range $key, $val := .Values.kafka_vars }}
          - name: {{ $key }}
            value: {{ $val | quote }}
        {{- end }}
        {{- if .Values.springArgs.overrideSpringArgs }}
        env:
          - name: spring_args
            value: {{ .Values.springArgs.value }}
        {{- end}}
        imagePullPolicy: {{ .Values.RegistryManager.image.pullPolicy }}
        name: {{ .Values.RegistryManager.name }}
        ports:
        - containerPort: 1030
          protocol: TCP
        lifecycle:
           preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X PUT "http://eureka:8761/eureka/apps/C-SOURCES/$HOSTNAME:c-sources:1030/status?value=OUT_OF_SERVICE"
        {{- if .Values.RegistryManager.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:1030/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: {{ .Values.RegistryManager.readinessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.RegistryManager.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.RegistryManager.readinessProbe.periodSeconds }}
          {{- end}}
        resources:
{{ toYaml .Values.RegistryManager.resources | indent 10 }}
      restartPolicy: {{ .Values.RegistryManager.restartPolicy }}
      {{- if .Values.RegistryManager.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.RegistryManager.serviceAccount.name }}
      {{- end}}
      {{- if .Values.RegistryManager.securityContext.enabled }}
      securityContext:
{{ toYaml .Values.RegistryManager.securityContext.settings | indent 8 }}
      {{- end}}
      terminationGracePeriodSeconds: {{ .Values.RegistryManager.terminationGracePeriodSeconds }}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.name }}
status: {}
{{- end }}