ingressType: nginx # traefik or nginx

alerta:
  externalPath: /alerta/ # note: must end with /
  externalHostname: testing.industry-fusion.com
keycloak:
  adminName: admin
  externalAuthService:   # put here the *external* keycloak name, i.e. through ingress 
    protocol: "https:"
    domainname: testing.industry-fusion.com
    path: /auth/ # keycloak internal do not change
    # pathPrefix: /keycloak-iff/ # for ingress, must end with /

db:
  pvSize: 1Gi
  podInstances: 2
  backupBucket: db-backup
  backupNum: "5"
  cloneEnabled: false

scorpio:
  externalHostname: testing.industry-fusion.com
  externalProtocol: "http:"
  externalPath: /scorpio/
  heap_min:
    Xms: "-Xms64M"
    Xmx: "-Xmx64M"
  heap_main:
    Xms: "-Xms64M"
    Xmx: "-Xmx64M"
  hpa:
    enabled: false
  resources_min:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  resources_main:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

certmanager:
  secret: prod-cert-tls
  issuer: letsencrypt-prod

flink:
  taskmanagers: 1
  jobmanager: 1
  defaultParalellism: 1
  bucket: flink

minio:
  enabled: true
  storageSize: 10G

kafka:
  storage:
    type: persistent-claim
    size: 20Gi
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
  resources:
    requests:
      memory: 400Mi
      cpu: 200m
    limits:
      memory: 1000Mi
      cpu: 800m
  jvmOptions:
    "-Xmx": "500m"
  name: my-cluster
  config:
    logRetentionHours: 24

kafkaBridge:
  debezium:
    replicaCount: 1
    listenTopicRetention: 28800000
    listenTopicCompression: gzip
    entityTopicRetention: 28800000
    attributesTopicRetention: 28800000
    attributesTopicCompression: gzip
  alerta:
    replicaCount: 1
    bulkTopicRetention: 300000
    listenTopicRetention: 28800000
  ngsildUpdates:
    replicaCount: 1
    tokenRefreshInterval: 200
    listenTopicRetention: 28800000
  timescaledb:
    postgresPort: 5432
    replicaCount: 1
    tokenRefreshInterval: 200
    listenTopicRetention: 28800000

velero:
  backupBucket: velero-backup
  region: de

redis:
  storage:
    size: 2Gi
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi

emqx:
  externalHostname: testing.industry-fusion.com

pgrest:
  externalPath: /pgrest/ # note: must end with /
  externalHostname: testing.industry-fusion.com
  dbPool: 10 # note: must not be more than max_connections in Postgres DB, default is 10