mainVersion: v0.6.0-beta.1
mainRepo: ibn40
mainRegistry: docker.io
namespace: iff
pullSecretCredentials: regcred
externalRegistry: docker.io
externalRegistry2: quay.io
externalRegistry3: registry.opensource.zalan.do
externalRegistry4: ghcr.io

db:
  teamId: acid
  clusterSvcPostfix: cluster
  svcPort: "5432"
  dbUser: "ngb"
  dbReaderUser: "dbreader"

ontology:
  baseUri: https://industryfusion.github.io/contexts/staging/example/v0.1/
 