namespace: iff
ingressType: traefik # or nginx
keycloak:
  adminName: admin
  externalAuthService:   # put here the *external* keycloak name, i.e. through ingress 
    protocol: http
    domainname: keycloak.local
    path: /auth
  internalAuthService: 
    name: keycloak-discovery
    port: 8080
    path: /auth
  alertaRealm: alerta
  alertaClient: alerta-ui
  alertaClientSecret: x8M59QRO8dgG3PYJ4UR03qh5CBBzfLUa
db:
  teamId: acid
  clusterSvcPostfix: cluster
  pvSize: 1Gi
  podInstances: 2
  alertaDb: monitoring
  dbUser: ngb
  secretPostfix: credentials.postgresql.acid.zalan.do
ingress:
  scorpio: ngsild.local
scorpio:
  gatewaySvc: 
    name: gateway
    port: 9090
certmanager:
  secret: selfsigned-cert-tls
  issuer: letsencrypt-self